services:
  - type: web
    name: tabla-periodica-biblia
    runtime: node
    region: oregon
    plan: free
    buildCommand: cd tabla-periodica-biblia/app && npm install && npm run build
    startCommand: cd tabla-periodica-biblia/app && npm start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
